name: Publish model

on:
  workflow_dispatch:
    inputs:
      image:
        description: "The OCI image name. This must not include a tag or digest."
        type: string
        default: "docker.io/lmrs2/bh-aisec-model-inference"
      digest:
        description: "The OCI image digest. The image digest of the form '<algorithm>:<digest>' (e.g. 'sha256:abcdef...')"
        type: string
        default: "sha256:b694e56c2c4c60a3e771d7dde95e26c282e1bd6a30a7e8a46c6dc986c54be906"
      environment:
        type: choice
        description: Environment to use
        options: 
        - prod
        - staging

permissions: read-all

defaults:
  run:
    shell: bash

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}-inference

jobs:
  publish:
    permissions:
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
      contents: read # To read the repo.
    uses: lmrs2/bh-aisec-organization/.github/workflows/image-publisher.yml@main
    with:
      environment: ${{ inputs.environment }}
      image: ${{ inputs.image }}
      digest: ${{ inputs.digest }}
      # Use name rather than env variable because env are not available for reusable workflows.
      registry-username: lmrs2
      #registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #registry-password: ${{ secrets.GITHUB_TOKEN }}
